basePath: /
definitions:
  model.Channel:
    properties:
      Address:
        type: string
      CivilCode:
        type: string
      DeviceId:
        type: string
      Manufacturer:
        type: string
      Model:
        type: string
      Name:
        type: string
      Owner:
        type: string
      ParentID:
        type: string
      Parental:
        type: string
      RegisterWay:
        type: string
      SafetyWay:
        type: string
      Secrecy:
        type: string
      Status:
        type: string
      createdAt:
        type: string
      id:
        type: integer
      updatedAt:
        type: string
    type: object
  model.Device:
    properties:
      createdAt:
        type: string
      deviceId:
        type: string
      domain:
        type: string
      expires:
        type: string
      firmware:
        type: string
      id:
        type: integer
      ip:
        type: string
      keepalive:
        type: string
      manufacturer:
        type: string
      model:
        type: string
      name:
        type: string
      offline:
        type: integer
      port:
        type: string
      registerTime:
        type: string
      transport:
        type: string
      updatedAt:
        type: string
    type: object
  model.DeviceControl:
    properties:
      channelId:
        description: 通道id
        type: string
      command:
        description: 控制的命令，取值为：left、right、down、up、downright、downleft、upright、upleft、zoomin、zoomout
        type: string
      deviceId:
        description: 设备id
        type: string
      horizonSpeed:
        description: 水平方向移动速度，取值：0-255
        type: integer
      verticalSpeed:
        description: 垂直方向移动速度，取值：0-255
        type: integer
      zoomSpeed:
        description: 变倍控制速度，取值：0-255
        type: integer
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:18080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Go-GB28181是一个基于GB28181-2016标准实现的网络视频平台，用 Go 语言实现，实现了 SIP 协议和信令服务器。
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go-GB28181项目前端APi接口
  version: "1.0"
paths:
  /channel/list/{device}:
    get:
      description: 给定一个设备id，返回该设备下的所有通道信息
      parameters:
      - description: 设备id
        in: path
        name: device
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Channel'
            type: array
      summary: 返回一个设备下的所有通道信息
      tags:
      - channel
  /control/ptz:
    get:
      consumes:
      - application/json
      description: 根据传入的控制方向、控制速度等参数去控制摄像头的云台
      parameters:
      - description: 控制云台对象
        in: body
        name: deviceControl
        required: true
        schema:
          $ref: '#/definitions/model.DeviceControl'
      produces:
      - application/json
      responses:
        "200":
          description: model.Account
          schema:
            type: string
      summary: 控制摄像头的云台
      tags:
      - control
  /device/list:
    get:
      consumes:
      - application/json
      description: 返回连接到该服务的所有设备
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Device'
            type: array
      summary: 返回连接到该服务的所有设备
      tags:
      - device
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
