# gb服务器的配置
sip:
    # [必须修改] 本机的IP
    ip: 192.168.1.223

    # [可选] 28181服务监听的端口
    port: 5060

    # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
    # 后两位为行业编码，定义参照附录D.3
    # 3701020049标识山东济南历下区 信息行业接入
    # [可选]
    domain: 4401020049

    # [可选]
    id: 44010200492000000001

    # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
    password: admin123
    user-agent: gb

## 客户端配置
client:
    # 客户端ip地址
    ip: 192.168.1.223

    # 客户端端口
    port: 5061

    # 设备id
    id: 44010200491118000001

    # 设备用户id
    user: 44010200491118000001

    # 密码
    password: admin123

    # 注册有效期/秒
    register-expire: 3600

    # 注册间隔，最小60秒
    register-interval: 60

    # 心跳间隔，最小5秒
    heartbeat-interval: 5

    # 最大心跳超时次数
    max-heartbeat-timeout: 3

    # 传输协议，只允许填写tcp和udp
    transport: tcp


    # 报警相关配置
    alert:
        # 报警输入编码数量
        num: 5
        list:
        - 44444444444444444444
    # 通道相关信息
    channel:
        num: 5
        list:
        - 44010200491318000011
        - 44010200491318000012
        - 44010200491318000013
        - 44010200491318000014
        - 44010200491318000015

# [可选] 日志配置, 一般不需要改
log:
    # 日志级别
    level: info
    # 日志路径
    path: ./log
    # 日志文件名称
    file: gbclient.log
    # 日志文件在轮换之前的最大大小，M为单位
    maxSize: 1
    # 是要保留的最大旧日志文件数。默认是保留所有旧的日志文件
    maxBackups: 30
    # 是根据文件名中编码的时间戳保留旧日志文件的最大天数。
    maxAge: 30