# 作为 28181 服务器的配置
sip:
    # [必须修改] 本机的IP
    ip: 192.168.1.223

    # [可选] 28181服务监听的端口
    port: 5060

    # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
    # 后两位为行业编码，定义参照附录D.3
    # 3701020049标识山东济南历下区 信息行业接入
    # [可选]
    domain: 4401020049

    # [可选]
    id: 44010200492000000001

    # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
    password: admin123
    user-agent: gb


# [可选] 日志配置, 一般不需要改
log:
    # 日志级别
    level: info
    # 日志路径
    path: ./log
    # 日志文件名称
    file: gbctl.log
    # 日志文件在轮换之前的最大大小，M为单位
    maxSize: 1
    # 是要保留的最大旧日志文件数。默认是保留所有旧的日志文件
    maxBackups: 30
    # 是根据文件名中编码的时间戳保留旧日志文件的最大天数。
    maxAge: 30